//---------------------------------------------------------------------------

#ifndef mainH
#define mainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Buttons.hpp>
#include <ComCtrls.hpp>
#include <Menus.hpp>
#include <Graphics.hpp>
#include <ImgList.hpp>
#include <Grids.hpp>

//---------------------------------------------------------------------------
class TFormMain : public TForm
{
__published:	// IDE-managed Components
        TPopupMenu *PopupMenuFormMain;
        TMenuItem *N1;
        TMenuItem *N2;
        TMenuItem *N3;
        TMenuItem *N4;
        TImageList *ImageListvs;
        TImageList *ImageListhm;
        TMainMenu *MainMenu1;
        TMenuItem *NClose;
        TMenuItem *N7;
        TMenuItem *N8;
        TMenuItem *N9;
        TMenuItem *N10;
        TBitBtn *BitCalcs;
        TMenuItem *N12;
        TMenuItem *N13;
        TLabel *Label36;
        TMenuItem *N14;
        TMenuItem *N15;
        TMenuItem *N16;
        TMenuItem *N17;
        TMenuItem *N18;
        TMenuItem *N19;
        TPanel *PanelFormulaAl;
        TGroupBox *GroupBox11;
        TImage *Image11;
        TLabel *Label42;
        TLabel *Label39;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label43;
        TEdit *EditTkoef1;
        TEdit *EditTX1;
        TEdit *EditTY1;
        TEdit *EditTZ1;
        TEdit *EditTKs;
        TBitBtn *BitBtn1fz;
        TGroupBox *GroupBox10;
        TImage *Image12;
        TLabel *Label44;
        TLabel *Label46;
        TLabel *Label47;
        TLabel *Label45;
        TEdit *EditTkoef2;
        TEdit *EditTX2;
        TEdit *EditTY2;
        TEdit *EditTZ2;
        TBitBtn *BitBtn2V1;
        TGroupBox *GroupBox9;
        TImage *Image16;
        TLabel *Label35;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TEdit *EditTkoef3;
        TEdit *EditTX3;
        TEdit *EditTY3;
        TEdit *EditTZ3;
        TEdit *EditTsm1;
        TBitBtn *BitBtn3V2;
        TGroupBox *GroupBox8;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label56;
        TLabel *Label57;
        TImage *Image17;
        TEdit *EditTkoef4;
        TEdit *EditTX4;
        TEdit *EditTY4;
        TEdit *EditTZ4;
        TEdit *EditTsm2;
        TBitBtn *BitBtn4P;
        TMenuItem *N20;
        TMenuItem *N21;
        TPanel *PanelStMaterial;
        TGroupBox *GroupBoxStMaterial;
        TRadioButton *RadioButton1;
        TRadioButton *RadioButton2;
        TRadioButton *RadioButton3;
        TRadioButton *RadioButton4;
        TRadioButton *RadioButton5;
        TStringGrid *StringGridTab;
        TMemo *Memo1;
        TMenuItem *N22;
        TBitBtn *BitBtnStMaterialOut;
        TStaticText *StaticTextMaterial;
        TPanel *PanelTemp;
        TStaticText *StaticText1;
        TLabel *Label58;
        TStringGrid *StringGridT;
        TLabel *Label59;
        TMenuItem *N23;
        TMenuItem *N24;
        TMenuItem *N5;
        TMenuItem *N25;
        TImageList *ImageListTiDir;
        TMenuItem *N26;
        TMenuItem *NMesWin;
        TBitBtn *BitBtnHelp;
        TPanel *PanelCalc;
        TPageControl *PageControlParam;
        TTabSheet *TabSheet1;
        TLabel *Label1;
        TLabel *Label2;
        TLabel *LabelB;
        TLabel *LabelT;
        TLabel *Label25;
        TImage *Imagevs;
        TLabel *Label26;
        TLabel *Label23;
        TLabel *Label31;
        TImage *Image4;
        TLabel *LabelVc;
        TLabel *Labelfz;
        TComboBox *BaseD;
        TComboBox *BaseZ;
        TEdit *BaseB;
        TEdit *BaseT;
        TComboBox *ComboBoxStContact;
        TEdit *EditStk;
        TComboBox *ComboBoxStkpd;
        TGroupBox *GroupBox13;
        TLabel *Label34;
        TLabel *Label29;
        TLabel *Label30;
        TEdit *EditStKc11;
        TEdit *EditStMc;
        TBitBtn *BitBtnStMaterial;
        TStaticText *StaticTextStMaterial;
        TEdit *EditStGamma0;
        TEdit *BaseVc;
        TEdit *Basefz;
        TTabSheet *TabSheet2;
        TLabel *Label3;
        TLabel *Label48;
        TLabel *Label6;
        TLabel *Label60;
        TLabel *Label61;
        TLabel *Label62;
        TLabel *Label63;
        TComboBox *ComboBoxMaterial;
        TComboBox *ComboBoxTkpd;
        TComboBox *ComboBoxRa;
        TTabSheet *TabSheet3;
        TPageControl *PageControlMethods;
        TTabSheet *TabSheetStandard;
        TGroupBox *GroupBox3;
        TImage *Image6;
        TLabel *Label21;
        TEdit *EditStQ;
        TBitBtn *BitBtnSt2;
        TGroupBox *GroupBox4;
        TImage *Image7;
        TLabel *Label18;
        TImage *Image3;
        TLabel *Label19;
        TImage *Image10;
        TEdit *EditStVf;
        TEdit *EditStfz;
        TBitBtn *BitBtnSt4;
        TGroupBox *GroupBox5;
        TImage *Image5;
        TLabel *Label22;
        TImage *Image8;
        TLabel *Label32;
        TLabel *Label33;
        TLabel *Label17;
        TEdit *EditStP;
        TEdit *EditStKc;
        TBitBtn *BitBtnSt5;
        TGroupBox *GroupBox6;
        TLabel *Label20;
        TImage *Imagehm;
        TLabel *Label27;
        TLabel *Label28;
        TEdit *EditSthm2;
        TCheckBox *CheckBoxhm2;
        TEdit *EditaeDc;
        TBitBtn *BitBtnSt3;
        TGroupBox *GroupBox7;
        TImage *Image1;
        TLabel *Label4;
        TImage *Image2;
        TLabel *Label5;
        TImage *Image9;
        TEdit *EditStn;
        TEdit *EditStVc;
        TBitBtn *BitBtnSt1;
        TTabSheet *TabSheetTechAl;
        TGroupBox *GroupBox2;
        TLabel *Label7;
        TLabel *Label8;
        TLabel *Label9;
        TLabel *Label10;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label15;
        TLabel *Label16;
        TImage *Image13;
        TImage *Image14;
        TImage *Image15;
        TImage *Image18;
        TImage *Image19;
        TEdit *EditSz;
        TEdit *EditV1;
        TEdit *EditV2;
        TEdit *EditTm;
        TEdit *Editn;
        TEdit *EditF;
        TEdit *EditPz;
        TEdit *EditMz;
        TEdit *EditNp;
        TComboBox *EditV;
        TBitBtn *BitBtnPanelAl;
        TGroupBox *GroupBox12;
        TLabel *Label37;
        TLabel *Label38;
        TEdit *EditK;
        TEdit *EdittD;
        TBitBtn *BitBtnAlTm1;
        TBitBtn *BitBtnAln1;
        TBitBtn *BitBtnAlF1;
        TBitBtn *BitBtnAlPz1;
        TBitBtn *BitBtnAlMz1;
        TBitBtn *BitBtnAlNp1;
        TPanel *PanelForestP;
        TStringGrid *StringGridP;
        TStaticText *StaticText2;
        TTabSheet *TabSheetTechTi;
        TRadioGroup *RadioGroupTiMaterial;
        TRadioGroup *RadioGroupTiCoolnt;
        TRadioGroup *RadioGroupTiSurface;
        TRadioGroup *RadioGroupTiSkin;
        TLabel *Label24;
        TComboBox *ComboBoxTiTime;
        TComboBox *BaseAlD;
        TComboBox *BaseAlZ;
        TEdit *BaseAlB;
        TEdit *BaseAlT;
        TStatusBar *StatusBarMes;
        TLabel *Label64;
        TComboBox *BaseTiD;
        TLabel *Label65;
        TComboBox *BaseTiZ;
        TLabel *Label66;
        TComboBox *BaseTiL;
        TBitBtn *BitBtnGraphic;
        TTabSheet *TabSheet4;
        TImage *Image20;
        TEdit *EditTifz;
        TComboBox *ComboBoxTiMaterial;
        TLabel *Label67;
        TImageList *ImageListSurface;
        TImage *ImageSurface;
        TImage *Image21;
        TImage *Image22;
        TEdit *EditTin;
        TEdit *EditTiF;
        TMenuItem *N11;
        TLabel *Label68;
        TLabel *Label69;
        TEdit *BaseTiB;
        TEdit *BaseTiT;
        TLabel *Label70;
        TLabel *Label71;
        TLabel *Label72;
        TLabel *Label73;
        TEdit *EditTiVc;
        TRadioGroup *RadioGroupTiDirection;
        TImage *ImageDirection;
        TImageList *ImageListDirection;
        TRadioGroup *RadioGroupTiTypeDetal;
        TImage *ImageTiVbase;
        TGroupBox *GroupBox1;
        TLabel *Label74;
        TImage *ImageTiVsmall;
        TEdit *EditTiVsmall;
        TImageList *ImageListTiMaterial;
        TImageList *ImageListTiVsmall;
        TLabel *Label75;
        TLabel *Label76;
        TEdit *EditTinsmall;
        TEdit *EditTiFsmall;
        TLabel *Label77;
        TLabel *Label78;
        TImage *Image23;
        TImage *Image24;
        TEdit *EditTiMz;
        TEdit *EditTiNct;
        TLabel *Label80;
        TEdit *EditTiNctsmall;
        TLabel *Label83;
        TLabel *Label84;
        TComboBox *BaseTihz;
        TRadioGroup *RadioGroupTiPz;
        TLabel *Label81;
        TLabel *Label82;
        TEdit *EditTiPxcoeff;
        TEdit *EditTiPycoeff;
        TImage *Image25;
        TImage *Image26;
        TEdit *EditTiPx;
        TEdit *EditTiPy;
        TEdit *EditTiP;
        TImage *Image27;
        TComboBox *TabMach;
        TLabel *Label79;
        TLabel *Label85;
        TEdit *EditStPn;
        TLabel *Label86;
        TLabel *Label87;
        TEdit *EditStM;
        TLabel *Label88;
        TLabel *Label89;
        void __fastcall BitCalcsClick(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall N1Click(TObject *Sender);
        void __fastcall N2Click(TObject *Sender);
        void __fastcall N4Click(TObject *Sender);
        void __fastcall N13Click(TObject *Sender);
        void __fastcall ComboBoxStContactChange(TObject *Sender);
        void __fastcall CheckBoxhm2Click(TObject *Sender);
        void __fastcall BitBtnStMaterialClick(TObject *Sender);
        void __fastcall BitBtnHelpClick(TObject *Sender);
        void __fastcall Image9Click(TObject *Sender);
        void __fastcall Image10Click(TObject *Sender);
        void __fastcall ComboBoxMaterialChange(TObject *Sender);
        void __fastcall RadioButton1Click(TObject *Sender);
        void __fastcall RadioButton2Click(TObject *Sender);
        void __fastcall RadioButton3Click(TObject *Sender);
        void __fastcall RadioButton4Click(TObject *Sender);
        void __fastcall RadioButton5Click(TObject *Sender);
        void __fastcall BitBtnStMaterialOutClick(TObject *Sender);
        void __fastcall StringGridTabSelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
        void __fastcall BitBtnPanelAlClick(TObject *Sender);
        void __fastcall ComboBoxRaChange(TObject *Sender);
        void __fastcall BitBtnAlTm1Click(TObject *Sender);
        void __fastcall BitBtnAln1Click(TObject *Sender);
        void __fastcall BitBtnAlF1Click(TObject *Sender);
        void __fastcall BitBtnAlPz1Click(TObject *Sender);
        void __fastcall BitBtnAlMz1Click(TObject *Sender);
        void __fastcall BitBtnAlNp1Click(TObject *Sender);
        void __fastcall BitBtn1fzClick(TObject *Sender);
        void __fastcall BitBtn2V1Click(TObject *Sender);
        void __fastcall BitBtn3V2Click(TObject *Sender);
        void __fastcall BitBtn4PClick(TObject *Sender);
        void __fastcall EditVChange(TObject *Sender);
        void __fastcall N25Click(TObject *Sender);
        void __fastcall NMesWinClick(TObject *Sender);
        void __fastcall PageControlParamChange(TObject *Sender);
        void __fastcall BitBtnGraphicClick(TObject *Sender);
        void __fastcall PageControlMethodsChange(TObject *Sender);
        void __fastcall RadioGroupTiSurfaceClick(TObject *Sender);
        void __fastcall RadioGroupTiDirectionClick(TObject *Sender);
        void __fastcall ComboBoxTiMaterialChange(TObject *Sender);
        void __fastcall RadioGroupTiPzClick(TObject *Sender);
        void __fastcall TabMachChange(TObject *Sender);
        void __fastcall BitBtnSt1Click(TObject *Sender);
        void __fastcall BitBtnSt4Click(TObject *Sender);
        void __fastcall BitBtnSt2Click(TObject *Sender);
        void __fastcall BitBtnSt3Click(TObject *Sender);
        void __fastcall BitBtnSt5Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        void CalcStandart(TObject *Sender);
        int CalcStnV(TObject *Sender);
        int CalcStQ(TObject *Sender);
        int CalcSthm(TObject *Sender);
        int CalcStFSz(TObject *Sender);
        int CalcStNctMz(TObject *Sender);
        void CalcTechAl(TObject *Sender);
        int CalcTechAlSz(TObject *Sender);
        int CalcTechAlV1(TObject *Sender);
        int CalcTechAlV2(TObject *Sender);
        int CalcTechAlV0(TObject *Sender);
        int CalcTechAlTemp(TObject *Sender);
        int CalcTechAln(TObject *Sender);
        int CalcTechAlF(TObject *Sender);
        int CalcTechAlPz(TObject *Sender);
        int CalcTechAlMz(TObject *Sender);
        int CalcTechAlNct(TObject *Sender);
        void CalcTechTi(TObject *Sender);
        void OutputMessage(AnsiString s);
        __fastcall TFormMain(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TFormMain *FormMain;
//---------------------------------------------------------------------------
#endif
